# COMMON VARIABLES
zone="europe-west1-c"
topicName="fil-topic"
subscriptionName="kvittering-sub"
bucketName="faggruppe-bucket-strg"
functionBucketName="function-bucket-strg"
project="faggruppemote"
region="EU"
entryPoint="handler"
runtime="nodejs16"
project="infrastructu-tut-bew-wo-2022"